export const feedbackCategories = [
    "Bug Report",
    "Feature Request",
    "UI/UX Improvement",
    "Performance Issue",
    "Security Concern",
    "Account Issue",
    "Login/Signup Problem",
    "Content Moderation Feedback",
    "Report Inappropriate Content",
    "Suggestion for New Tools",
    "Mobile Experience Issue",
    "Privacy Concern",
    "Community Guidelines Feedback",
    "Post/Comment Error",
    "Profile Customization Issue",
    "Accessibility Feedback",
    "General Feedback",
    "Other",
];